---
- hosts: all
  user: dcmuser
  vars:
    medical_images_dir: /srv/data/images
    docker_network: dcmnet
    pacs_db_container_name: pacsdb
    dicom_server_image_name: dicomsrv:latest
    dicom_server_container_name: dicomsrv
    owner_build_dir: dcmuser
    build_source_dir: /srv/dicomsrv_build_dir/
  roles:
    - docker_network_role
    # - database_role
    - dicomsrv_role

